# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import serverside_pb2 as serverside__pb2


class AvgWeightsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddMyWeights = channel.unary_unary(
                '/serverside.AvgWeights/AddMyWeights',
                request_serializer=serverside__pb2.AddMyWeightsRequest.SerializeToString,
                response_deserializer=serverside__pb2.AddMyWeightsResponse.FromString,
                )
        self.GetReleaseWeights = channel.unary_unary(
                '/serverside.AvgWeights/GetReleaseWeights',
                request_serializer=serverside__pb2.GetReleaseWeightsRequest.SerializeToString,
                response_deserializer=serverside__pb2.GetReleaseWeightsResponse.FromString,
                )


class AvgWeightsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddMyWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReleaseWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvgWeightsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddMyWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMyWeights,
                    request_deserializer=serverside__pb2.AddMyWeightsRequest.FromString,
                    response_serializer=serverside__pb2.AddMyWeightsResponse.SerializeToString,
            ),
            'GetReleaseWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReleaseWeights,
                    request_deserializer=serverside__pb2.GetReleaseWeightsRequest.FromString,
                    response_serializer=serverside__pb2.GetReleaseWeightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'serverside.AvgWeights', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AvgWeights(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddMyWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverside.AvgWeights/AddMyWeights',
            serverside__pb2.AddMyWeightsRequest.SerializeToString,
            serverside__pb2.AddMyWeightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReleaseWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/serverside.AvgWeights/GetReleaseWeights',
            serverside__pb2.GetReleaseWeightsRequest.SerializeToString,
            serverside__pb2.GetReleaseWeightsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
